## Crear nuestro dataset

In [1]:
import pandas as pd

ventas = pd.DataFrame({
    "vendedor": [
        "Ana", "Luis", "Ana", "Carlos", "Luis", "Ana",
        "Carlos", "Luis", "Ana", "Carlos", "Luis", "Ana",
        "Luis", "Carlos", "Ana", "Carlos", "Luis", "Ana",
        "Carlos", "Luis", "Ana", "Carlos", "Luis", "Carlos",
        "Ana", "Luis"
    ],

    "producto": [
        "Laptop", "Mouse", "Monitor", "Laptop", "Tablet", "Mouse",
        "Monitor", "Laptop", "Tablet", "Monitor", "Mouse", "Laptop",
        "Monitor", "Laptop", "Mouse", "Tablet", "Laptop", "Monitor",
        "Laptop", "Tablet", "Laptop", "Mouse", "Monitor", "Tablet",
        "Mouse", "Laptop"
    ],

    "monto": [
        15000, 500, 4500, 18000, 5000, 700,
        4500, 16000, 6500, 4700, 800, 17000,
        4200, 15500, 550, 4800, 14000, 4300,
        19000, 6200, 14500, 750, 4100, 5100,
        600, 17500
    ]
})

print(ventas)

   vendedor producto  monto
0       Ana   Laptop  15000
1      Luis    Mouse    500
2       Ana  Monitor   4500
3    Carlos   Laptop  18000
4      Luis   Tablet   5000
5       Ana    Mouse    700
6    Carlos  Monitor   4500
7      Luis   Laptop  16000
8       Ana   Tablet   6500
9    Carlos  Monitor   4700
10     Luis    Mouse    800
11      Ana   Laptop  17000
12     Luis  Monitor   4200
13   Carlos   Laptop  15500
14      Ana    Mouse    550
15   Carlos   Tablet   4800
16     Luis   Laptop  14000
17      Ana  Monitor   4300
18   Carlos   Laptop  19000
19     Luis   Tablet   6200
20      Ana   Laptop  14500
21   Carlos    Mouse    750
22     Luis  Monitor   4100
23   Carlos   Tablet   5100
24      Ana    Mouse    600
25     Luis   Laptop  17500

¿Cuánto vendimos?

In [2]:
print(f"El total de ventas de la empresa es: {ventas['monto'].sum()} ")

El total de ventas de la empresa es: 204300

In [3]:
print(f"La venta más alta fue: {ventas["monto"].max()})
print(f"La venta más alta fue: {ventas["monto"].max()})

SyntaxError: f-string: unmatched '[' (3128969352.py, line 1)

¿Cuál fue la venta promedio?

¿Cuál fue la venta más alta? y ¿Cuál fue la venta más baja?

¿Y si queremos obtener todas estas métricas al mismo tiempo?  
Múltiples funciones de agregación sobre una columna

Agregación con groupby() y funciones simples  

 Permite agrupar los datos según una variable categórica (ej. monto)  
  
 y aplicar una métrica matemática sobre una variable numérica.

## Agregación con funciones personalizada

Función para calcular el rango de precios de venta

In [ ]:
def calculate_range(x):
   

range_quantity = ventas['monto'].agg(calculate_range)
print(f"El rango de la columna 'Ventas' es:\n{range_quantity}")

## El problema real

La empresa pregunta:

¿Cuánto vendió cada vendedor?

## Varias métricas por grupo

In [ ]:
resumen = (
    ventas
    .groupby("vendedor")["monto"]
    .agg(["sum", "mean", "max", "min", "count"])
)

print(resumen)

⭐ Reto: ¿quién tiene el mejor desempeño?

- Calcular el total vendido por producto

- Obtener por producto:

-número de ventas  
-venta total  
-promedio  
-venta máxima

agg() con nombres personalizados

In [ ]:
resumen = (
    ventas
    .groupby("vendedor")
    .agg(
        ventas_totales=("monto", "sum"),
        venta_promedio=("monto", "mean"),
        venta_maxima=("monto", "max"),
        numero_ventas=("monto", "count")
    )
)

print(resumen)

Agrupar por dos variables

¿Qué vendedor tuvo la venta promedio más alta?

Aplicar condiciones después de agregar  
"La empresa considera que un vendedor tiene buen desempeño si sus ventas totales superan $65,000."

In [ ]:
resumen = (
    ventas
    .groupby("vendedor")
    .agg(
        ventas_totales=("monto", "sum"),
        numero_ventas=("monto", "count")
    )
)
print(resumen)

## Trabajar con un dataset real

In [8]:
df_salarios = pd.read_csv('../Salary_Data.csv')
df_salarios

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [10]:
df_cleaned = df_salarios.dropna()  # Elimina todas las filas con al menos un NaN

¿La educación está relacionada con el salario?

In [11]:
df_cleaned.groupby("Education Level")["Salary"].mean()

Education Level
Bachelor's           124767.658730
Bachelor's Degree     85174.886093
High School           36706.694196
Master's             157604.166667
Master's Degree      125075.333969
PhD                  165684.828947
phD                  120000.000000
Name: Salary, dtype: float64

In [12]:
df_cleaned.groupby("Education Level")["Salary"].agg([
    "count",
    "mean",
    "median",
    "min",
    "max"
])

                   count           mean    median       min       max
Education Level
Bachelor's           756  124767.658730  130000.0     350.0  250000.0
Bachelor's Degree   2265   85174.886093   75000.0     500.0  250000.0
High School          448   36706.694196   30000.0   25000.0  166109.0
Master's             288  157604.166667  177500.0   40000.0  200000.0
Master's Degree     1572  125075.333969  122000.0   32000.0  228000.0
PhD                 1368  165684.828947  170000.0     579.0  250000.0
phD                    1  120000.000000  120000.0  120000.0  120000.0

Observa el resultado y escribe una conclusión de máximo dos líneas.

##  2 Variables
¿Cómo cambia el salario promedio dependiendo del nivel educativo y género?

## El analista de ventas

In [ ]:
ventas = pd.DataFrame({
    "vendedor": [
        "Ana", "Luis", "Carlos", "Ana",
        "Luis", "Carlos", "Ana", "Luis",
        "Carlos", "Ana"
    ],
    
    "producto": [
        "Laptop", "Mouse", "Laptop", "Tablet",
        "Laptop", "Mouse", "Monitor", "Tablet",
        "Monitor", "Mouse"
    ],
    
    "monto": [
        15000, 500, 18000, 5000,
        16000, 700, 4500, 5000,
        4500, 800
    ]
})

# Actividad  

## Obtener:  
- Total de ventas.
- Venta promedio.
- Venta máxima.
- Venta mínima. 

## Obtener las ventas totales por:  
- vendedor
- producto  

## Crear un DataFrame con:  
- ventas totales
- venta promedio
- venta máxima
- cantidad de ventas

para cada vendedor. 


## Reto final

Responder:  
¿Quién es el mejor vendedor si consideramos como criterio el total vendido?

Y:  
¿Quién tiene la venta promedio más alta?  
¿Las dos respuestas son iguales? ¿Qué significa esto?